### ISSUE TITLE
Support Laravel Vapor

### ISSUE THREAD

**Issue by mwisner** [laravel/tinker#77]
```bash
➜  backend git:(feat/vapor-work) ✗ vapor command  

 What command would you like to execute:
 > tinker

==> Executing Function...

Status Code: 1

Output:

[2019-10-04 13:54:50] staging.ERROR: Writing to //.config/psysh is not allowed. {"exception":"[object] (ErrorException(code: 0): Writing to //.config/psysh is not allowed. at /var/task/vendor/psy/psysh/src/ConfigPaths.php:228)
[stacktrace]
#0 /var/task/vendor/sentry/sentry/src/ErrorHandler.php(386): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(1024, 'Writing to //.c...', '/var/task/vendo...', 228)
#1 [internal function]: Sentry\\ErrorHandler->handleError(1024, 'Writing to //.c...', '/var/task/vendo...', 228, Array)
#2 /var/task/vendor/psy/psysh/src/ConfigPaths.php(228): trigger_error('Writing to //.c...', 1024)
#3 /var/task/vendor/psy/psysh/src/Configuration.php(376): Psy\\ConfigPaths::touchFileWithMkdir('//.config/psysh...')
#4 /var/task/vendor/psy/psysh/src/Configuration.php(405): Psy\\Configuration->setHistoryFile('//.config/psysh...')
#5 /var/task/vendor/psy/psysh/src/Configuration.php(542): Psy\\Configuration->getHistoryFile()
#6 /var/task/vendor/psy/psysh/src/Shell.php(90): Psy\\Configuration->getReadline()
#7 /var/task/vendor/laravel/tinker/src/Console/TinkerCommand.php(53): Psy\\Shell->__construct(Object(Psy\\Configuration))
#8 [internal function]: Laravel\\Tinker\\Console\\TinkerCommand->handle()
#9 /var/task/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#10 /var/task/vendor/laravel/framework/src/Illuminate/Support/helpers.php(522): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#11 /var/task/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): value(Object(Closure))
#12 /var/task/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#13 /var/task/vendor/laravel/framework/src/Illuminate/Container/Container.php(591): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#14 /var/task/vendor/laravel/framework/src/Illuminate/Console/Command.php(202): Illuminate\\Container\\Container->call(Array)
#15 /var/task/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#16 /var/task/vendor/laravel/framework/src/Illuminate/Console/Command.php(189): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#17 /var/task/vendor/symfony/console/Application.php(915): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 /var/task/vendor/symfony/console/Application.php(272): Symfony\\Component\\Console\\Application->doRunCommand(Object(Laravel\\Tinker\\Console\\TinkerCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 /var/task/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 /var/task/vendor/laravel/framework/src/Illuminate/Console/Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#22 /var/task/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#23 {main}
"} 

   ErrorException  : Writing to //.config/psysh is not allowed.

  at /var/task/vendor/psy/psysh/src/ConfigPaths.php:228
    224|             @\mkdir($dir, 0700, true);
    225|         }
    226| 
    227|         if (!\is_dir($dir) || !\is_writable($dir)) {
  > 228|             \trigger_error(\sprintf('Writing to %s is not allowed.', $dir), E_USER_NOTICE);
    229| 
    230|             return false;
    231|         }
    232|

  Exception trace:

  1   trigger_error("Writing to //.config/psysh is not allowed.")
      /var/task/vendor/psy/psysh/src/ConfigPaths.php:228

  2   Psy\ConfigPaths::touchFileWithMkdir("//.config/psysh/psysh_history")
      /var/task/vendor/psy/psysh/src/Configuration.php:376

  Please use the argument -v to see more details.

Function Logs:
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
